services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DOMAIN_NAME=localhost
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    restart: unless-stopped

volumes:
  n8n_data:
